### ISSUE TITLE
Question on installation

### ISSUE THREAD

**Issue by MoJo2600** [eikona-media/contao-usercentrics#1]
is it enough to install the plugin or is there something additionally that has to be installed. I added the usercentrics tag to the head section of the page. But is there anything else?

Best, Christian

**Comment by rabauss** [comment]
I've updated the readme with some configuration instructions - this should help ;-)
see: https://github.com/eikona-media/contao-usercentrics#configuration

The usercentrics tag is added automatically via the config in the site structure!

**Comment by MoJo2600** [comment]
Thank you!
